### PR TITLE
Properly reject promise when script loading fails

### LINKED ISSUE #4: error during loading script should reject promise
Currently we simply resolve on `error` events instead of rejecting the promise, which should be done so we can properly handle any errors caused by ad blockers for example.

### PR DESCRIPTION
**Pull request by TiddoLangerak**
Closes #4

@Magnetme/monolith - RFR

### CODE REVIEW

**Comment by TiddoLangerak** [comment]
Fly-by: update package.json to include links to the Github repo

**Comment by erwinvaneyk** [comment]
lgtm :+1:

**Comment by AlexKolpa** [comment]
You now do the try-catch in the javascript code, but in the script you inject this isn't done. Is that on purpose? Does this still load the default variation without crashing/hanging?

**Comment by alexnederlof** [comment]
whoops, read Kolpa's comment to late. Sorry, revert if this shouldn't have been merged

**Comment by alexnederlof** [comment]
Also, I don't know how/if to release this @TiddoLangerak @wouter-willems

**Comment by AlexKolpa** [comment]
@alexnederlof needs to be published to npm, but I believe only @TiddoLangerak has the credentials right now since npm only has support for paid organizations.

**Comment by TiddoLangerak** [comment]
@AlexKolpa - I assume that with the injected script you mean the script in the iframe? If so, then that's on purpose. The iframe loads the Google Analytics api via a regular script tag. We rely on the order of script tags there for execution, i.e. our own code is in a script tag after the GA script. If the GA script isn't loaded then the `cxApi` simply isn't available, and we fall back to the default variation [here](https://github.com/Magnetme/experiments/blob/master/src/index.js#L123). There's no need to do try-catch here.

**Comment by TiddoLangerak** [comment]
@alexnederlof - I'll fix the credentials somewhere in the near future.

**Comment by AlexKolpa** [comment]
aah ok, thanks for the explanation @TiddoLangerak!

**Pull request merged**
